/* 
A coloured triangle is created from different rows of colours (Red, Green or Blue). Successive rows, each containing one 
fewer colour than the last, are generated by considering the two touching colours in the previous row. If these colours are identical, the same colour is used in the new row. If colours are different, the missing colour is used in the new row. This process continues untill 
a single colour is generated in the final row.

Different possibilities of colours are:

Colours Touching:        G G        B G        R G        B R
New colour:               G          R          B          G
With a bigger example:

R R G B R G B B
 R B R G B R B
  G G B R G G
   G R G B G
    B B R R
     B G R
      R B
       G
Goal
Create a function which takes first row of the triangle as an input and returns the final colour which would appear at the bottom row. In 
above example, given input "RRGBRGBB" will return "G".
If you are only given one colour as the input, return that colour.
There will be no exception handling case.
Examples
colouredTriangle("B") ➞ "B"

colouredTriangle("GB") ➞ "R"

colouredTriangle("RBRGBRB") ➞ "G" */


function colouredTriangle(row) {
if(row.length==1){
  return row
}else{
  let arr=row.split("")
  let result=[]
  
  while(result.length!=1){
    result=[]
    for(let i=0;i<arr.length;i++){
      if(arr[i]==arr[i+1]){
        result.push(arr[i])
      }else if((arr[i]=="B" && arr[i+1]=="G")|| (arr[i]=="G" && arr[i+1]=="B")){
        result.push("R")
      }else if((arr[i]=="R" && arr[i+1]=="G")|| (arr[i]=="G" && arr[i+1]=="R")){
        result.push("B")
      }else if((arr[i]=="B" && arr[i+1]=="R")|| (arr[i]=="R" && arr[i+1]=="B")){
       result.push("G")
      }
      
    }
  
   
    arr=result
    
  }
 return result[0]
}

}

console.log(colouredTriangle('RRGBRGBB'))
